#!/bin/bash

if [ $DATABASE_HOST ]; then
cat >~/.kettle/repositories.xml <<EOF;
<?xml version="1.0" encoding="UTF-8"?>
<repositories>
  <connection>
    <name>connection</name>
    <server>$DATABASE_HOST</server>
    <type>$DATABASE_TYPE</type>
    <access>Native</access>
    <database>$DATABASE_DATABASE</database>
    <port>$DATABASE_PORT</port>
    <username>$DATABASE_USER</username>
    <password>Encrypted $DATABASE_PASSWORD</password>
    <servername/>
    <data_tablespace/>
    <index_tablespace/>
    <attributes>
      <attribute><code>EXTRA_OPTION_MYSQL.defaultFetchSize</code><attribute>500</attribute></attribute>
      <attribute><code>EXTRA_OPTION_MYSQL.useCursorFetch</code><attribute>true</attribute></attribute>
      <attribute><code>FORCE_IDENTIFIERS_TO_LOWERCASE</code><attribute>N</attribute></attribute>
      <attribute><code>FORCE_IDENTIFIERS_TO_UPPERCASE</code><attribute>N</attribute></attribute>
      <attribute><code>IS_CLUSTERED</code><attribute>N</attribute></attribute>
      <attribute><code>PORT_NUMBER</code><attribute>$DATABASE_PORT</attribute></attribute>
      <attribute><code>QUOTE_ALL_FIELDS</code><attribute>N</attribute></attribute>
      <attribute><code>STREAM_RESULTS</code><attribute>Y</attribute></attribute>
      <attribute><code>SUPPORTS_BOOLEAN_DATA_TYPE</code><attribute>N</attribute></attribute>
      <attribute><code>USE_POOLING</code><attribute>N</attribute></attribute>
    </attributes>
  </connection>
  <repository>
    <id>KettleDatabaseRepository</id>
    <name>repository</name>
    <description>repository</description>
    <connection>connection</connection>
  </repository>
</repositories>
EOF
fi

exec $*
